import fs from 'fs';
import path from 'path';
import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { getFirestore, doc, setDoc, writeBatch } from 'firebase/firestore';
import cfg from '../firebase-applet-config.json' with { type: 'json' };

// Raw questions from user prompt for ND1 Nursing: Primary Health Care (PHC) CBT Set 3
const rawInputQuestions = [
  { q: "[Set 3] In which year and at what conference was the Primary Health Care approach formally adopted globally?", options: [{text: "1975 Geneva Declaration", correct: false}, {text: "1978 Alma-Ata Declaration", correct: true, rationale: "The Alma-Ata Declaration in USSR in September 1978 established PHC globally."}, {text: "1988 Abuja Health Policy", correct: false}, {text: "1992 NPHCDA Decree", correct: false}] },
  { q: "[Set 3] Who is widely acknowledged as the 'Father of Primary Health Care in Nigeria'?", options: [{text: "Gen. Yakubu Gowon", correct: false}, {text: "Prof. Olikoye Ransome-Kuti", correct: true, rationale: "Prof. Olikoye Ransome-Kuti championed PHC implementation as Minister of Health."}, {text: "Gen. Ibrahim Babangida", correct: false}, {text: "Maurice Leing", correct: false}] },
  { q: "[Set 3] Which decree established the National Primary Health Care Development Agency (NPHCDA) in 1992?", options: [{text: "Decree No. 10 of 1988", correct: false}, {text: "Decree No. 29 of 1992", correct: true, rationale: "Decree No. 29 of 1992 set up the NPHCDA in Nigeria."}, {text: "Decree No. 4 of 1999", correct: false}, {text: "Decree No. 15 of 1975", correct: false}] },
  { q: "[Set 3] How many essential elements or components of PHC were outlined in the Alma-Ata Declaration?", options: [{text: "Four elements", correct: false}, {text: "Eight essential elements", correct: true, rationale: "The Alma-Ata Declaration outlined eight essential components."}, {text: "Twelve elements", correct: false}, {text: "Six elements", correct: false}] },
  { q: "[Set 3] Which of the following is NOT among the basic principles of Primary Health Care?", options: [{text: "Equitable distribution of resources", correct: false}, {text: "Maximum curative centralization", correct: true, rationale: "PHC avoids centralized curative bias, favoring decentralized preventive care."}, {text: "Community involvement and participation", correct: false}, {text: "Appropriate technology", correct: false}] },
  { q: "[Set 3] According to Helvic (1981), what is defined as a primary group living in a household in intimate relationship?", options: [{text: "A Community", correct: false}, {text: "A Family", correct: true, rationale: "Family is defined by Helvic as the basic primary group sharing household proximity."}, {text: "A Ward Development Committee", correct: false}, {text: "A Health Facility Committee", correct: false}] },
  { q: "[Set 3] In Nigeria's three-tier healthcare system, Primary Health Care is primarily the statutory responsibility of:", options: [{text: "The Federal Government", correct: false}, {text: "The State Government", correct: false}, {text: "The Local Government Area (LGA)", correct: true, rationale: "Local governments manage primary healthcare services through LGA health departments."}, {text: "Private Mission Hospitals", correct: false}] },
  { q: "[Set 3] What is the recommended population size served by a standard Primary Health Centre in rural Nigeria?", options: [{text: "1,000 population", correct: false}, {text: "5,000 population", correct: false}, {text: "30,000 population", correct: true, rationale: "A standard Primary Health Centre serves roughly 30,000 people."}, {text: "100,000 population", correct: false}] },
  { q: "[Set 3] What is the maximum walking distance recommended for families to reach a PHC facility?", options: [{text: "1 kilometer", correct: false}, {text: "5 kilometers", correct: true, rationale: "Families should be within a 5km walking distance of a PHC facility."}, {text: "15 kilometers", correct: false}, {text: "30 kilometers", correct: false}] },
  { q: "[Set 3] Secondary healthcare in Nigeria (General and Specialist Hospitals) is managed by:", options: [{text: "Local Government Councils", correct: false}, {text: "State Ministries of Health via Hospitals Management Boards", correct: true, rationale: "Secondary healthcare falls under state government management."}, {text: "Federal Ministry of Health", correct: false}, {text: "Village Development Committees", correct: false}] },
  { q: "[Set 3] Traditional Birth Attendants (TBAs) acquire their skills primarily through:", options: [{text: "Formal university nursing degrees", correct: false}, {text: "Traditional knowledge, inheritance, or apprenticeship", correct: true, rationale: "TBA skills are acquired through traditional apprenticeship and experience."}, {text: "Federal medical residency", correct: false}, {text: "NPHCDA administrative workshops", correct: false}] },
  { q: "[Set 3] Frontline voluntary healthcare workers who serve in villages to provide basic first aid are:", options: [{text: "Village Health Workers (VHWs)", correct: true, rationale: "VHWs are frontline volunteer workers serving villages and neighborhoods."}, {text: "Consultant Surgeons", correct: false}, {text: "State Health Commissioners", correct: false}, {text: "Pharmacy Technicians", correct: false}] },
  { q: "[Set 3] Community Health Extension Workers (CHEWs) are trained to provide:", options: [{text: "Preventive, promotive, and rehabilitative primary care", correct: true, rationale: "CHEWs deliver primary healthcare services focusing on prevention and promotion."}, {text: "Exclusively neuro-surgical operations", correct: false}, {text: "Macro-economic budget planning", correct: false}, {text: "International diplomatic health policies", correct: false}] },
  { q: "[Set 3] Who serves as the political head of the Local Government Health Department?", options: [{text: "The Supervisory Counselor for Health", correct: true, rationale: "The supervisory counselor for health is the political head responsible to the LGA chairman."}, {text: "The Medical Officer of Health", correct: false}, {text: "The Community Health Officer", correct: false}, {text: "The State Governor", correct: false}] },
  { q: "[Set 3] What is the professional leadership role of a Public Health Nurse in Primary Health Care?", options: [{text: "Identifying population health issues, health education, and immunization coordination", correct: true, rationale: "PHNs identify population health issues and coordinate community health outreach."}, {text: "Managing state civil service pensions", correct: false}, {text: "Enforcing customs border tariffs", correct: false}, {text: "Engineering water borehole construction", correct: false}] },
  { q: "[Set 3] Community mobilization in primary health care is defined as:", options: [{text: "Imposing government health infrastructure", correct: false}, {text: "A participatory process of arousing interest to solve community problems actively", correct: true, rationale: "Mobilization encourages people to take active participation in health solutions."}, {text: "A purely financial taxation collection mechanism", correct: false}, {text: "Mandatory quarantine", correct: false}] },
  { q: "[Set 3] According to Adegeorge (1989), community mobilization assists people to:", options: [{text: "Rely entirely on foreign donor funding", correct: false}, {text: "Identify real needs and recognize that most resources are within community competence", correct: true, rationale: "People recognize needed resources are within their competence."}, {text: "Migrate permanently to urban cities", correct: false}, {text: "Abandon cultural norms", correct: false}] },
  { q: "[Set 3] In the 3-stage community mobilization process, what is the focus of Stage 1 (Fact Finding)?", options: [{text: "Collecting vital information on leaders, traditions, and community problems", correct: true, rationale: "Stage 1 involves gathering background statistics, leadership, and belief data."}, {text: "Demolishing roadside markets", correct: false}, {text: "Conducting major surgery", correct: false}, {text: "Issuing international passports", correct: false}] },
  { q: "[Set 3] What is the recommended composition and leadership requirement for a Ward Development Committee?", options: [{text: "15 members appointed by federal government", correct: false}, {text: "8 members representing ward councilor, facility head, community, youth, and women leaders", correct: true, rationale: "WDCs consist of 8 key community representatives with specific leadership offices."}, {text: "Only medical doctors", correct: false}, {text: "Elected international delegates", correct: false}] },
  { q: "[Set 3] What guideline is recommended regarding female representation in WDC membership?", options: [{text: "Women should form 30% of membership, with a woman holding the treasurer office", correct: true, rationale: "Women should form 30% of WDC membership and serve as treasurer."}, {text: "Women are barred from committees", correct: false}, {text: "Women must make up 100%", correct: false}, {text: "Gender composition is ignored", correct: false}] },
  { q: "[Set 3] Community diagnosis is best described as:", options: [{text: "A surgical procedure", correct: false}, {text: "The process of determining the health status of a community and the factors responsible for it", correct: true, rationale: "Community diagnosis evaluates community health status and causal factors."}, {text: "A financial audit", correct: false}, {text: "A political manifesto", correct: false}] },
  { q: "[Set 3] In anthropometric measurement where age is known, which charts and indices are utilized?", options: [{text: "Blood pressure charts", correct: false}, {text: "Growth chart or Road to Health chart (weight for age)", correct: true, rationale: "When age is known, weight-for-age is plotted on growth charts."}, {text: "Mid-upper arm circumference exclusively", correct: false}, {text: "Urine sugar strips", correct: false}] },
  { q: "[Set 3] When the exact age of a child is unknown during nutritional assessment, which measurement is standard?", options: [{text: "Mid-Upper Arm Circumference (MUAC)", correct: true, rationale: "MUAC is used for under-five nutritional screening when age is unknown."}, {text: "Chest X-ray imaging", correct: false}, {text: "Electrocardiogram", correct: false}, {text: "Surgical biopsy", correct: false}] },
  { q: "[Set 3] What percentage range on the Road to Health chart indicates that a child is underweight?", options: [{text: "80% - 100%", correct: false}, {text: "60% - 80%", correct: true, rationale: "60% - 80% indicates underweight and high malnutrition risk."}, {text: "Below 60%", correct: false}, {text: "Above 120%", correct: false}] },
  { q: "[Set 3] What is the primary purpose of a 'Situation Analysis' in PHC?", options: [{text: "To determine the ability of health services to respond to problems identified through community diagnosis", correct: true, rationale: "Situation analysis examines health service capability and resources."}, {text: "To construct highways", correct: false}, {text: "To prosecute health law offenders", correct: false}, {text: "To manufacture vaccines", correct: false}] },
  { q: "[Set 3] How is Health Education successfully represented as an equation in community health?", options: [{text: "Health Education = Medication + Surgery", correct: false}, {text: "Health Education = Health Information + Motivation + Action", correct: true, rationale: "Health Education equals information plus motivation leading to positive action."}, {text: "Health Education = Posters + Radio", correct: false}, {text: "Health Education = Theory - Practice", correct: false}] },
  { q: "[Set 3] What is the primary difference between Health Information and Health Education?", options: [{text: "Health information is passive dissemination, whereas health education motivates recipient action and behavior change", correct: true, rationale: "Health education successfully imparts information resulting in behavioral adoption."}, {text: "Health education is only for doctors", correct: false}, {text: "There is no difference", correct: false}, {text: "Health information requires surgery", correct: false}] },
  { q: "[Set 3] Which of the following are categorized as Information, Education, and Communication (IEC) support materials?", options: [{text: "Surgical forceps", correct: false}, {text: "Posters, leaflets, flyers, and billboards", correct: true, rationale: "Posters, leaflets, flyers, and billboards convey public health messaging."}, {text: "Microscope slides", correct: false}, {text: "Ambulance tires", correct: false}] },
  { q: "[Set 3] Behavior Change Communication (BCC) in public health is defined as:", options: [{text: "An interactive process with individuals or communities to develop strategies promoting positive health behaviors", correct: true, rationale: "BCC is an interactive process encouraging healthier practices."}, {text: "A rigid administrative memo", correct: false}, {text: "A clinical drug prescription chart", correct: false}, {text: "An architectural blueprint", correct: false}] },
  { q: "[Set 3] Which key factor affects the acceptability and effectiveness of IEC support materials in a community?", options: [{text: "Language (materials must be in local language and appropriate literacy level)", correct: true, rationale: "Materials must use local languages and appropriate literacy levels."}, {text: "Foreign classical languages", correct: false}, {text: "Complex medical jargon", correct: false}, {text: "Keeping materials hidden", correct: false}] },
  { q: "[Set 3] History taking in clinical nursing practice is defined as:", options: [{text: "A random casual conversation", correct: false}, {text: "The systematic collection of a patient's personal, medical, and social information", correct: true, rationale: "History taking acquires accurate medical data to establish care."}, {text: "Checking hospital financial ledgers", correct: false}, {text: "Inventory count", correct: false}] },
  { q: "[Set 3] What time format and documentation practice is essential for safe patient record keeping?", options: [{text: "Using the 24-hour clock, signing, and dating each entry", correct: true, rationale: "Accurate records require the 24-hour clock, signatures, and dates."}, {text: "Writing in pencil without dates", correct: false}, {text: "Omitting patient identification", correct: false}, {text: "Discarding notes after 24 hours", correct: false}] },
  { q: "[Set 3] What is a primary purpose of maintaining nursing and agency reports in PHC?", options: [{text: "To aid in studying health conditions, planning, and showing services rendered", correct: true, rationale: "Reports summarize services, aid health studies, and assist planning."}, {text: "Decorative wall artwork", correct: false}, {text: "Wrapping supplies", correct: false}, {text: "Replacing prescription sheets", correct: false}] },
  { q: "[Set 3] What quality characterizes a good nursing report?", options: [{text: "Time-saving, clear, organized, avoiding unnecessary words", correct: true, rationale: "Good reports are timely, organized, clear, and concise."}, {text: "Ambiguous and lengthy", correct: false}, {text: "Unreadable handwriting", correct: false}, {text: "Unverified hearsay", correct: false}] },
  { q: "[Set 3] Standing orders in primary healthcare clinical practice refer to:", options: [{text: "Pre-approved protocols allowing nurses to initiate specific treatments under defined circumstances", correct: true, rationale: "Standing orders guide nurses in prompt clinical assessment and care."}, {text: "Physical exercise drills", correct: false}, {text: "Seating arrangements", correct: false}, {text: "Musical background tracks", correct: false}] },
  { q: "[Set 3] Which international body co-sponsored the landmark 1978 Alma-Ata conference?", options: [{text: "WHO and UNICEF", correct: true, rationale: "WHO and UNICEF jointly sponsored the Alma-Ata conference."}, {text: "UNESCO and NATO", correct: false}, {text: "Red Cross only", correct: false}, {text: "World Bank only", correct: false}] },
  { q: "[Set 3] The basic unit of healthcare delivery closest to the grassroots in Nigeria is the:", options: [{text: "Primary Health Care Centre / Clinic", correct: true, rationale: "PHC clinics are the closest health points to rural grassroots populations."}, {text: "University Teaching Hospital", correct: false}, {text: "Federal Ministry of Health", correct: false}, {text: "State Specialist Hospital", correct: false}] },
  { q: "[Set 3] What is the primary objective of Maternal and Child Health (MCH) within PHC services?", options: [{text: "To reduce morbidity and mortality rates among mothers and children", correct: true, rationale: "MCH focuses on safeguarding maternal and child health metrics."}, {text: "To provide cosmetic surgeries", correct: false}, {text: "To issue birth certificates only", correct: false}, {text: "To manage geriatric retirement homes", correct: false}] },
  { q: "[Set 3] Which vaccine is typically administered at birth or within the first two weeks of life in Nigeria's EPI schedule?", options: [{text: "BCG and Oral Polio Vaccine (OPV 0)", correct: true, rationale: "BCG and OPV 0 are given at birth."}, {text: "Tetanus toxoid booster", correct: false}, {text: "Yellow fever vaccine", correct: false}, {text: "Adult meningitis jab", correct: false}] },
  { q: "[Set 3] Cold chain maintenance is critical in immunization programs to ensure:", options: [{text: "Vaccines remain potent and effective from manufacturing to administration", correct: true, rationale: "Cold chain preserves vaccine potency against temperature degradation."}, {text: "Vaccines freeze into ice blocks", correct: false}, {text: "Ampoules look attractive", correct: false}, {text: "Electricity bills are lowered", correct: false}] },
  { q: "[Set 3] What does the acronym 'PHC' stand for in professional healthcare training?", options: [{text: "Public Health Control", correct: false}, {text: "Primary Health Care", correct: true, rationale: "PHC stands for Primary Health Care."}, {text: "Private Hospital Consortium", correct: false}, {text: "Paramedic Hygiene Center", correct: false}] },
  { q: "[Set 3] In community entry, why is it essential to pay a courtesy call to traditional rulers and community leaders?", options: [{text: "To gain entry acceptance, trust, and community cooperation", correct: true, rationale: "Respecting traditional leadership secures community entry and cooperation."}, {text: "To collect personal financial taxes", correct: false}, {text: "To convert them to health workers", correct: false}, {text: "To inspect their personal residential houses", correct: false}] },
  { q: "[Set 3] Which of the following represents a biological determinant of community health?", options: [{text: "Age structure and genetic disease predisposition of the population", correct: true, rationale: "Age, sex, and genetics constitute biological determinants."}, {text: "Tarred asphalt roads", correct: false}, {text: "Political party manifestos", correct: false}, {text: "Stock market exchange rates", correct: false}] },
  { q: "[Set 3] Environmental sanitation as an element of PHC primarily encompasses:", options: [{text: "Safe water supply, excreta disposal, and vector control", correct: true, rationale: "Environmental health covers water, sanitation, and waste disposal."}, {text: "Space satellite launches", correct: false}, {text: "Musical concert organization", correct: false}, {text: "Automotive vehicle repairs", correct: false}] },
  { q: "[Set 3] Essential drugs availability is component number what in the original Alma-Ata PHC elements?", options: [{text: "Component 8", correct: true, rationale: "Provision of essential drugs is the 8th element of PHC."}, {text: "Component 1", correct: false}, {text: "Component 3", correct: false}, {text: "Component 5", correct: false}] },
  { q: "[Set 3] What is the primary role of a Community Health Officer (CHO) in a PHC facility?", options: [{text: "Supervising clinical care, managing facility resources, and coordinating primary health programs", correct: true, rationale: "CHOs provide clinical leadership and administrative supervision in PHC centers."}, {text: "Flying aerial medical rescue helicopters", correct: false}, {text: "Drafting national legislative bills", correct: false}, {text: "Conducting forensic autopsies", correct: false}] },
  { q: "[Set 3] Epidemiology in public health is defined as:", options: [{text: "The study of the distribution and determinants of health-related states or events in specified populations", correct: true, rationale: "Epidemiology examines disease distribution and determinants in populations."}, {text: "The treatment of skin rashes", correct: false}, {text: "The surgical repair of bones", correct: false}, {text: "The manufacturing of hospital beds", correct: false}] },
  { q: "[Set 3] An endemic disease is best described as:", options: [{text: "A disease constantly present in a particular region or population group", correct: true, rationale: "Endemic diseases remain baseline constant within a specific geographic area."}, {text: "A sudden worldwide outbreak", correct: false}, {text: "A disease that has been completely eradicated", correct: false}, {text: "A temporary seasonal allergy", correct: false}] },
  { q: "[Set 3] An epidemic refers to:", options: [{text: "An unexpected sudden increase in the number of disease cases above normal expectancy in a community", correct: true, rationale: "Epidemics represent disease spikes surpassing normal baseline expectancy."}, {text: "A normal baseline health condition", correct: false}, {text: "A genetic blood disorder", correct: false}, {text: "A chronic nutritional deficiency", correct: false}] },
  { q: "[Set 3] A pandemic is characterized by:", options: [{text: "An epidemic spreading over multiple countries or continents, affecting a large number of people", correct: true, rationale: "Pandemics cross international boundaries to affect worldwide populations."}, {text: "An infection isolated to a single hospital ward", correct: false}, {text: "A localized village outbreak", correct: false}, {text: "A non-communicable injury", correct: false}] },
  { q: "[Set 3] What is the primary vector responsible for transmitting malaria parasites to humans?", options: [{text: "Female Anopheles mosquito", correct: true, rationale: "Female Anopheles mosquitoes transmit Plasmodium parasites causing malaria."}, {text: "Aedes aegypti mosquito", correct: false}, {text: "Housefly", correct: false}, {text: "Tsetse fly", correct: false}] },
  { q: "[Set 3] What preventive strategy is heavily promoted in Nigerian PHC centers against malaria transmission in children and pregnant women?", options: [{text: "Insecticide-Treated Nets (ITNs) and Intermittent Preventive Treatment (IPT)", correct: true, rationale: "ITNs and IPT are primary anti-malarial preventive interventions in PHC."}, {text: "Regular consumption of saltwater", correct: false}, {text: "Wearing heavy winter woolen sweaters", correct: false}, {text: "Avoiding all physical exercise", correct: false}] },
  { q: "[Set 3] What is the main causative agent of tuberculosis (TB)?", options: [{text: "Mycobacterium tuberculosis", correct: true, rationale: "TB is caused by the bacterium Mycobacterium tuberculosis."}, {text: "Salmonella typhi", correct: false}, {text: "Vibrio cholerae", correct: false}, {text: "Streptococcus pneumoniae", correct: false}] },
  { q: "[Set 3] What is the standard treatment strategy recommended by WHO for managing diagnosed tuberculosis cases in PHC?", options: [{text: "Directly Observed Therapy, Short-course (DOTS)", correct: true, rationale: "DOTS ensures patient compliance and successful TB cure rates."}, {text: "Single aspirin tablet daily", correct: false}, {text: "Immediate major lung surgery", correct: false}, {text: "Herbal steam inhalation only", correct: false}] },
  { q: "[Set 3] Which nutritional deficiency disease is characterized by bilateral pitting edema, sparse hair, and a 'moon face' appearance?", options: [{text: "Kwashiorkor", correct: true, rationale: "Kwashiorkor is protein-deficiency malnutrition marked by edema and moon face."}, {text: "Marasmus", correct: false}, {text: "Scurvy", correct: false}, {text: "Rickets", correct: false}] },
  { q: "[Set 3] Severe wasting in children where weight-for-age falls drastically below 60% with old-man facial appearance is termed:", options: [{text: "Marasmus", correct: true, rationale: "Marasmus is severe energy/calorie deficiency causing severe muscle wasting."}, {text: "Kwashiorkor", correct: false}, {text: "Goiter", correct: false}, {text: "Beriberi", correct: false}] },
  { q: "[Set 3] What vitamin deficiency leads to night blindness and Bitot's spots in children?", options: [{text: "Vitamin A deficiency", correct: true, rationale: "Vitamin A is essential for eye health; deficiency causes xerophthalmia and night blindness."}, {text: "Vitamin C deficiency", correct: false}, {text: "Vitamin D deficiency", correct: false}, {text: "Vitamin K deficiency", correct: false}] },
  { q: "[Set 3] Oral Rehydration Therapy (ORT) is exceptionally effective in saving the lives of children suffering from:", options: [{text: "Severe dehydrating diarrhea and gastroenteritis", correct: true, rationale: "ORT replaces lost electrolytes and fluids caused by diarrheal dehydration."}, {text: "Hypertension", correct: false}, {text: "bone fractures", correct: false}, {text: "acute appendicitis", correct: false}] },
  { q: "[Set 3] What is the standard correct formula for mixing WHO Oral Rehydration Salts (ORS)?", options: [{text: "One sachet in one clean 1-litre bottle of water", correct: true, rationale: "Standard WHO ORS sachet is formulated to be dissolved in exactly 1 litre of clean water."}, {text: "One sachet in a small teacup of water", correct: false}, {text: "One sachet in a bathtub", correct: false}, {text: "One sachet in concentrated palm oil", correct: false}] },
  { q: "[Set 3] Exclusive breastfeeding entails feeding an infant with breastmilk only, without water or other foods, for how many months?", options: [{text: "First 6 months of life", correct: true, rationale: "Exclusive breastfeeding is recommended for the first 6 months of life."}, {text: "First 2 weeks only", correct: false}, {text: "First 3 months", correct: false}, {text: "First 12 months", correct: false}] },
  { q: "[Set 3] Complementary feeding alongside continued breastfeeding should ideally begin at what age?", options: [{text: "Completed 6 months of age", correct: true, rationale: "Complementary foods are introduced at 6 months alongside breastmilk to meet nutritional demands."}, {text: "At birth", correct: false}, {text: "At 3 months", correct: false}, {text: "At 2 years", correct: false}] },
  { q: "[Set 3] What is the primary purpose of conducting a home visit by a community health nurse?", options: [{text: "To assess family living conditions, health practices, and provide personalized nursing care in the home setting", correct: true, rationale: "Home visits provide direct insight into environmental and family health dynamics."}, {text: "To sell household furniture", correct: false}, {text: "To audit family income tax returns", correct: false}, {text: "To perform electrical wiring repairs", correct: false}] },
  { q: "[Set 3] In family health nursing, a family-focused genogram is used to:", options: [{text: "Map family pedigree, hereditary medical conditions, and generational relationships", correct: true, rationale: "Genograms chart family medical history and hereditary disease patterns across generations."}, {text: "Design architectural blueprints of houses", correct: false}, {text: "Calculate monthly clinic budgets", correct: false}, {text: "Track vehicle maintenance mileage", correct: false}] },
  { q: "[Set 3] An ecomap in community health nursing illustrates:", options: [{text: "The active relationships and connections between a family and external environmental systems", correct: true, rationale: "Ecomaps display family interactions with external community structures and social supports."}, {text: "Global weather climate patterns", correct: false}, {text: "Topographical relief maps of mountains", correct: false}, {text: "Road highway networks", correct: false}] },
  { q: "[Set 3] What is herd immunity in community vaccination programs?", options: [{text: "Resistance to the spread of a contagious disease within a population that results if a sufficiently high proportion of individuals are immune", correct: true, rationale: "High immunization coverage protects vulnerable unimmunized individuals in the community."}, {text: "Immunity exclusive to livestock farm animals", correct: false}, {text: "Immunity acquired through herbal concoctions", correct: false}, {text: "Natural resistance in newborn calves", correct: false}] },
  { q: "[Set 3] Which level of prevention includes early diagnosis and prompt treatment (such as screening tests and routine blood pressure checks)?", options: [{text: "Primary prevention", correct: false}, {text: "Secondary prevention", correct: true, rationale: "Secondary prevention focuses on early case finding, screening, and prompt treatment."}, {text: "Tertiary prevention", correct: false}, {text: "Quaternary prevention", correct: false}] },
  { q: "[Set 3] Tertiary prevention in community health nursing is best exemplified by:", options: [{text: "Rehabilitation, physiotherapy, and preventing complications in established chronic illnesses", correct: true, rationale: "Tertiary prevention minimizes disability and rehabilitates chronic disease patients."}, {text: "Administering routine immunization vaccines", correct: false}, {text: "Conducting blood pressure screening camps", correct: false}, {text: "Enforcing environmental sanitation laws", correct: false}] },
  { q: "[Set 3] Primary prevention measures are specifically designed to:", options: [{text: "Prevent the initial occurrence of a disease or injury before it happens (e.g., vaccination, health promotion)", correct: true, rationale: "Primary prevention stops disease onset before pathology begins."}, {text: "Cure terminal organ failure", correct: false}, {text: "Rehabilitate stroke patients", correct: false}, {text: "Perform surgical operations", correct: false}] },
  { q: "[Set 3] What is the vital role of the Health Facility Committee (HFC) at the PHC clinic level?", options: [{text: "Managing day-to-day facility maintenance, security, community support, and resolving local clinic challenges", correct: true, rationale: "HFCs oversee facility upkeep, security, and direct community-clinic collaboration."}, {text: "Passing federal senate laws", correct: false}, {text: "Manufacturing prescription drugs", correct: false}, {text: "Piloting commercial aircraft", correct: false}] },
  { q: "[Set 3] In health communication, 'feedback' refers to:", options: [{text: "The receiver's response that enables the sender to evaluate whether the message was understood", correct: true, rationale: "Feedback completes the communication loop confirming message comprehension."}, {text: "Complaining about clinic meal rations", correct: false}, {text: "Returning expired drugs to manufacturers", correct: false}, {text: "Refunding hospital consultation fees", correct: false}] },
  { q: "[Set 3] Which barrier to effective communication occurs when a health worker uses complex medical terminology with an illiterate patient?", options: [{text: "Semantic or language barrier", correct: true, rationale: "Jargon and complex vocabulary create semantic communication barriers."}, {text: "Physical acoustic barrier", correct: false}, {text: "Visual impairment barrier", correct: false}, {text: "Financial economic barrier", correct: false}] },
  { q: "[Set 3] What is the primary goal of school health programs within primary healthcare?", options: [{text: "Promoting physical, mental, and social well-being of school children through health instruction, services, and safe environment", correct: true, rationale: "School health targets student wellbeing, hygiene education, and screening."}, {text: "Conducting military combat drills", correct: false}, {text: "Running commercial school cafeterias for profit", correct: false}, {text: "Issuing university degrees", correct: false}] },
  { q: "[Set 3] Occupational health in primary healthcare focuses on:", options: [{text: "Protecting and promoting the physical and mental health of workers in their work environments", correct: true, rationale: "Occupational health prevents workplace hazards and promotes worker safety."}, {text: "Managing retirement pension accounts", correct: false}, {text: "Designing factory machinery", correct: false}, {text: "Negotiating worker salary strikes", correct: false}] },
  { q: "[Set 3] What is the primary purpose of maintaining an antenatal clinic (ANC) register in a PHC facility?", options: [{text: "To track pregnant mothers' attendance, clinical assessments, tetanus immunization status, and birth outcomes", correct: true, rationale: "ANC registers track maternal health progress, antenatal visits, and birth outcomes."}, {text: "To record hospital utility electricity bills", correct: false}, {text: "To inventory kitchen cooking utensils", correct: false}, {text: "To log visitor parking cars", correct: false}] },
  { q: "[Set 3] Which dangerous pregnancy complication is screened routinely during antenatal visits by checking blood pressure and urine protein?", options: [{text: "Pre-eclampsia / Eclampsia", correct: true, rationale: "High blood pressure and proteinuria during pregnancy indicate pre-eclampsia."}, {text: "Appendicitis", correct: false}, {text: "Common cold", correct: false}, {text: "Foot fracture", correct: false}] },
  { q: "[Set 3] What is the recommended minimum number of focused antenatal care (ANC) visits for a normal uncomplicated pregnancy?", options: [{text: "At least 4 visits (or 8 contacts under WHO guidelines)", correct: true, rationale: "Current standards recommend a minimum of 4 ANC visits (expanded to 8 contacts)."}, {text: "Only 1 visit at term", correct: false}, {text: "15 visits every week", correct: false}, {text: "No visits required", correct: false}] },
  { q: "[Set 3] What preventive medication is routinely given to pregnant women attending ANC in malaria-endemic regions like Nigeria?", options: [{text: "Intermittent Preventive Treatment in pregnancy using Sulfadoxine-Pyrimethamine (IPTp-SP)", correct: true, rationale: "IPTp-SP prevents malaria parasitemia in pregnant women."}, {text: "High-dose sleeping pills", correct: false}, {text: "Anticoagulant blood thinners", correct: false}, {text: "Chemotherapy drugs", correct: false}] },
  { q: "[Set 3] Why is routine iron and folic acid supplementation prescribed during antenatal care?", options: [{text: "To prevent maternal iron-deficiency anemia and neural tube defects in the developing fetus", correct: true, rationale: "Iron prevents maternal anemia while folic acid prevents neural tube defects."}, {text: "To darken hair color", correct: false}, {text: "To increase birth height", correct: false}, {text: "To cure tooth cavities", correct: false}] },
  { q: "[Set 3] What is the primary significance of the Partograph in intrapartum nursing care?", options: [{text: "To monitor labor progress, maternal condition, and fetal well-being graphically to prevent prolonged obstructed labor", correct: true, rationale: "The partograph provides a pictorial overview of labor to detect abnormalities early."}, {text: "To record hospital financial revenues", correct: false}, {text: "To map out hospital room architecture", correct: false}, {text: "To schedule staff holiday rosters", correct: false}] },
  { q: "[Set 3] What action should a nurse take when the alert line on a partograph is crossed into the action line during labor?", options: [{text: "Evaluate the woman thoroughly and transfer her to a secondary facility for expert obstetric intervention", correct: true, rationale: "Crossing the action line indicates abnormal labor progress requiring specialist management."}, {text: "Discharge the patient home", correct: false}, {text: "Ignore and wait for 24 hours", correct: false}, {text: "Administer sleeping tablets", correct: false}] },
  { q: "[Set 3] The immediate care given to a newborn baby right after delivery includes:", options: [{text: "Ensuring airway clearance, drying, keeping warm, APGAR scoring, and eye prophylaxis", correct: true, rationale: "Immediate newborn care focuses on resuscitation, warmth, and infection prevention."}, {text: "Immediate hot water bath immersion", correct: false}, {text: "Piercing baby ears", correct: false}, {text: "Feeding solid yam paste", correct: false}] },
  { q: "[Set 3] What does the 'A' in the acronym APGAR score stand for?", options: [{text: "Appearance (skin color)", correct: true, rationale: "A stands for Appearance (color), P for Pulse, G for Grimace, A for Activity, R for Respiration."}, {text: "Antibiotic", correct: false}, {text: "Anatomy", correct: false}, {text: "Altitude", correct: false}] },
  { q: "[Set 3] At what time intervals is the APGAR score routinely evaluated for a newborn baby?", options: [{text: "At 1 minute and 5 minutes after birth", correct: true, rationale: "APGAR is assessed at 1 and 5 minutes post-delivery to evaluate newborn transition."}, {text: "At 1 hour and 12 hours", correct: false}, {text: "At 24 days and 48 days", correct: false}, {text: "Every 10 seconds", correct: false}] },
  { q: "[Set 3] Postnatal care (PNC) for mother and baby should ideally include visits within what critical timeframe after delivery?", options: [{text: "Within 24 hours, 3 days, 7 days, and 6 weeks post-delivery", correct: true, rationale: "Early postnatal visits catch postpartum hemorrhage, sepsis, and newborn issues early."}, {text: "After 1 year", correct: false}, {text: "Only when complications arise", correct: false}, {text: "At age 5 school entry", correct: false}] },
  { q: "[Set 3] Family planning services within Primary Health Care contribute significantly to:", options: [{text: "Child spacing, preventing unwanted pregnancies, reducing maternal/child mortality, and improving family welfare", correct: true, rationale: "Family planning promotes child spacing and safeguards maternal health."}, {text: "Increasing national population congestion", correct: false}, {text: "Mandatory sterilization of all citizens", correct: false}, {text: "Eliminating all marriages", correct: false}] },
  { q: "[Set 3] Which of the following is categorized as a barrier method of contraception?", options: [{text: "Male and female condoms", correct: true, rationale: "Condoms act as physical barriers preventing sperm-ovum union and STIs."}, {text: "Combined oral contraceptive pills", correct: false}, {text: "Levonorgestrel intrauterine device", correct: false}, {text: "Progesterone hormone injection", correct: false}] },
  { q: "[Set 3] Long-Acting Reversible Contraception (LARC) methods include:", options: [{text: "Intrauterine Contraceptive Devices (IUCD) and hormonal implants", correct: true, rationale: "IUCDs and implants provide long-term reversible pregnancy protection."}, {text: "Emergency withdrawal method", correct: false}, {text: "Calendar rhythm counting", correct: false}, {text: "Daily oral pills", correct: false}] },
  { q: "[Set 3] What is the primary causative pathogen of cholera outbreaks in communities with poor sanitation?", options: [{text: "Vibrio cholerae", correct: true, rationale: "Cholera is an acute diarrheal infection caused by ingestion of Vibrio cholerae bacterium."}, {text: "Plasmodium falciparum", correct: false}, {text: "Mycobacterium leprae", correct: false}, {text: "HIV retrovirus", correct: false}] },
  { q: "[Set 3] What is the hallmark clinical presentation of cholera infection?", options: [{text: "Profuse painless watery diarrhea resembling 'rice-water' leading to rapid dehydration", correct: true, rationale: "Rice-water stools and rapid severe dehydration characterize cholera."}, {text: "High fever and joint rashes", correct: false}, {text: "Chronic dry hacking cough", correct: false}, {text: "Severe yellow jaundice", correct: false}] },
  { q: "[Set 3] What is the primary mode of transmission for human immunodeficiency virus (HIV)?", options: [{text: "Unprotected sexual intercourse, contact with infected blood, and vertical mother-to-child transmission", correct: true, rationale: "HIV is transmitted via sexual fluids, blood contact, and vertical transmission."}, {text: "Airborne droplet coughing", correct: false}, {text: "Handshake casual contact", correct: false}, {text: "Mosquito vector bites", correct: false}] },
  { q: "[Set 3] Prevention of Mother-to-Child Transmission (PMTCT) programs in PHC utilize:", options: [{text: "Antiretroviral prophylaxis, safe delivery practices, and infant feeding counseling", correct: true, rationale: "PMTCT protocols prevent vertical transmission from mother to baby."}, {text: "Quarantine isolation camps", correct: false}, {text: "Mandatory herbal concoctions", correct: false}, {text: "Surgical removal of lymph nodes", correct: false}] },
  { q: "[Set 3] What is the standard screening tool used in PHC clinics to detect abnormal blood pressure in adults?", options: [{text: "Sphygmomanometer and stethoscope", correct: true, rationale: "Blood pressure is measured using a sphygmomanometer cuff and stethoscope."}, {text: "Clinical thermometer", correct: false}, {text: "Glucometer strip", correct: false}, {text: "Weighing bathroom scale", correct: false}] },
  { q: "[Set 3] Hypertension is clinically defined in adults when resting blood pressure consistently exceeds:", options: [{text: "140 / 90 mmHg", correct: true, rationale: "BP readings of 140/90 mmHg or higher indicate hypertension."}, {text: "120 / 80 mmHg", correct: false}, {text: "90 / 60 mmHg", correct: false}, {text: "100 / 70 mmHg", correct: false}] },
  { q: "[Set 3] Diabetes mellitus screening in primary health care is commonly performed by checking:", options: [{text: "Blood glucose levels using a glucometer or urine testing for glycosuria", correct: true, rationale: "Glucometer blood tests and urine reagent strips screen for diabetes."}, {text: "Visual eye acuity", correct: false}, {text: "Hearing audio tones", correct: false}, {text: "Lung chest expansion", correct: false}] },
  { q: "[Set 3] What is the primary purpose of community health diagnosis data analysis?", options: [{text: "To prioritize community health problems and plan culturally acceptable interventions", correct: true, rationale: "Analyzing diagnosis data prioritizes community needs for effective intervention planning."}, {text: "To publish fictional novels", correct: false}, {text: "To decorate administrative office notice boards", correct: false}, {text: "To determine tax penalties", correct: false}] },
  { q: "[Set 3] In the implementation phase of a PHC project, community participation ensures:", options: [{text: "Sustainability, local ownership, and successful utilization of health services", correct: true, rationale: "Community involvement guarantees project sustainability and local ownership."}, {text: "Complete dependence on foreign loans", correct: false}, {text: "Exclusion of local chiefs", correct: false}, {text: "Rapid privatization of clinics", correct: false}] },
  { q: "[Set 3] What evaluation method is used to measure the immediate output and long-term impact of a PHC program?", options: [{text: "Comparing baseline survey indicators with post-intervention health statistics", correct: true, rationale: "Evaluations compare pre- and post-intervention indicators to measure impact."}, {text: "Guessing patient satisfaction numbers", correct: false}, {text: "Counting office chair furniture", correct: false}, {text: "Weighing medical record folders", correct: false}] },

  // Supplementary NUR 122 items to complete full 100 questions (matching 100-Question CBT standard)
  { q: "[Set 3] What is the recommended storage temperature range for standard refrigerated vaccines (e.g., Pentavalent, PCV, IPV) in PHC facilities?", options: [{text: "+2°C to +8°C", correct: true, rationale: "Refrigerated vaccines must be maintained strictly between +2°C and +8°C to prevent freezing or heat degradation."}, {text: "-20°C to -10°C", correct: false}, {text: "+15°C to +25°C", correct: false}, {text: "+37°C to +40°C", correct: false}] },
  { q: "[Set 3] The Bamako Initiative adopted in 1987 in Mali primarily aimed to achieve what in African primary healthcare?", options: [{text: "Universal access to essential drugs through community co-financing and revolving drug funds (RDF)", correct: true, rationale: "The Bamako Initiative established revolving drug funds to ensure continuous availability of essential drugs through community co-financing."}, {text: "Establishing private commercial health insurance for urban elites", correct: false}, {text: "Closing down rural health posts", correct: false}, {text: "Centralizing all drug purchases under foreign embassies", correct: false}] },
  { q: "[Set 3] In primary healthcare, what is the primary purpose of maintaining a 'Spot Map' of a catchment community?", options: [{text: "To geographically pinpoint disease clusters, environmental hazards, water points, and vulnerable households", correct: true, rationale: "Spot maps allow community health workers to visually track disease outbreaks, environmental sanitation risks, and service coverage."}, {text: "To serve as decorative clinic painting", correct: false}, {text: "To survey boundaries for real estate sales", correct: false}, {text: "To track road vehicle speed limits", correct: false}] }
];

async function run() {
  console.log(`Processing Set 3 (${rawInputQuestions.length} questions)...`);

  const dbPath = path.resolve('data/database.json');
  const dbData = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

  // Format questions 301 to 400
  const startIndex = 301;
  const newQuestions: any[] = [];
  const newQuestionIds: string[] = [];

  rawInputQuestions.forEach((item, idx) => {
    const qId = String(startIndex + idx);
    newQuestionIds.push(qId);

    const letters = ['A', 'B', 'C', 'D'];
    let correctKey = 'A';
    let detailedRationale = '';

    const formattedOptions = item.options.map((opt, optIdx) => {
      const letter = letters[optIdx] || 'A';
      if (opt.correct) {
        correctKey = letter;
        if (opt.rationale) detailedRationale = opt.rationale;
      }
      return {
        id: letter,
        text: opt.text
      };
    });

    const questionObj = {
      id: qId,
      subjectId: 'subj-phc',
      levelId: 'lvl-nd1',
      question: item.q,
      questionText: item.q,
      options: formattedOptions,
      correctAnswer: correctKey,
      rationale: detailedRationale || 'Correct as indicated by Primary Health Care curriculum and Alma-Ata principles.',
      clinicalPearl: 'Key high-yield concept for Nigerian Nursing Council and National Diploma examinations.',
      category: 'Primary Health Care',
      difficulty: 'medium',
      createdAt: new Date().toISOString()
    };

    newQuestions.push(questionObj);
  });

  // Remove any previous Set 3 questions if re-run
  dbData.questions = dbData.questions.filter((q: any) => Number(q.id) < 301 || Number(q.id) > 400);
  dbData.questions.push(...newQuestions);

  // Build the Set 3 CBT Exam
  const examId = 'cbt-phc-nur122-set3';
  const examObj = {
    id: examId,
    title: 'ND1 Nursing – Primary Health Care (PHC) CBT – Set 3',
    courseCode: 'NUR 122',
    department: 'Nursing',
    level: 'ND 1',
    levelId: 'lvl-nd1',
    subjectId: 'subj-phc',
    subjectName: 'Primary Health Care / NUR 122',
    description: 'Standardized 100-Question Timed CBT covering PHC fundamentals, community diagnosis, cold chain maintenance, Bamako initiative revolving drug funds, and maternal & child health (Set 3).',
    durationMinutes: 45,
    totalQuestions: 100,
    passingScore: 50,
    questionIds: newQuestionIds,
    instructions: 'Timed 45-minute standardized CBT exam. Covers PHC principles, community mobilization, health education, epidemiology, maternal and child health, immunization cold chain, and standing orders (Set 3). Select the single best answer for each question.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  const existingExamIdx = dbData.exams.findIndex((e: any) => e.id === examId);
  if (existingExamIdx >= 0) {
    dbData.exams[existingExamIdx] = examObj;
  } else {
    dbData.exams.push(examObj);
  }

  // Save database.json
  fs.writeFileSync(dbPath, JSON.stringify(dbData, null, 2), 'utf8');
  console.log(`Saved database.json successfully with ${dbData.questions.length} total questions and ${dbData.exams.length} exams.`);

  // Sync to Firestore
  console.log('Authenticating with Firebase for Firestore sync...');
  const app = initializeApp(cfg);
  const auth = getAuth(app);
  const firestore = getFirestore(app, (cfg as any).firestoreDatabaseId);

  try {
    const cred = await signInWithEmailAndPassword(auth, 'tiktokyhung@gmail.com', 'chiga4006#');
    console.log('Firebase authentication successful as:', cred.user.email);

    // Write Set 3 exam
    await setDoc(doc(firestore, 'exams', examId), examObj, { merge: true });
    console.log(`Exam ${examId} written to Firestore.`);

    // Batch commit questions in chunks of 50
    const chunkSize = 50;
    for (let i = 0; i < newQuestions.length; i += chunkSize) {
      const chunk = newQuestions.slice(i, i + chunkSize);
      const batch = writeBatch(firestore);
      chunk.forEach((q) => {
        const qRef = doc(firestore, 'questions', q.id);
        batch.set(qRef, q, { merge: true });
      });
      await batch.commit();
      console.log(`Committed questions chunk ${i + 1} to ${i + chunk.length} to Firestore.`);
    }

    console.log('All 100 questions for Set 3 successfully committed to Firestore!');
    process.exit(0);
  } catch (err) {
    console.error('Firestore sync error:', err);
    process.exit(1);
  }
}

run();
